controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    husky_velocity_controller:
      type: diff_drive_controller/DiffDriveController

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_group_position_controller:
      type: forward_command_controller/ForwardCommandController

    rh_p12_rn_position:
      type: effort_controllers/JointGroupEffortController

    rh_r2_position:
      type: effort_controllers/JointGroupEffortController

    rh_l1_position:
      type: effort_controllers/JointGroupEffortController

    rh_l2_position:
      type: effort_controllers/JointGroupEffortController

husky_velocity_controller:
  ros__parameters:
    left_wheel_names: ['front_left_wheel', 'rear_left_wheel']
    right_wheel_names: ['front_right_wheel', 'rear_right_wheel']

    wheel_separation: 0.5708
    wheel_radius: 0.1651

    wheel_separation_multiplier: 1.875
    wheel_radius_multiplier: 1.0

    publish_rate: 50.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]

    open_loop: false
    enable_odom_tf: false

    cmd_vel_timeout: 0.5
    #publish_limited_velocity: true
    #velocity_rolling_window_size: 10

    # Velocity and acceleration limits
    linear.x.has_velocity_limits: true
    linear.x.has_acceleration_limits: true
    linear.x.has_jerk_limits: false
    linear.x.max_velocity: 1.0
    linear.x.min_velocity: -1.0
    linear.x.max_acceleration: 3.0
    linear.x.min_acceleration: -3.0

    angular.z.has_velocity_limits: true
    angular.z.has_acceleration_limits: true
    angular.z.has_jerk_limits: false
    angular.z.max_velocity: 2.0
    angular.z.min_velocity: -2.0
    angular.z.max_acceleration: 6.0
    angular.z.min_acceleration: -6.0

arm_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    state_publish_rate: 25.0
    action_monitor_rate: 10.0

    allow_partial_joints_goal: false
    open_loop_control: false
    allow_integration_in_goal_trajectories: true

    constraints:
      stopped_velocity_tolerance: 0.05
      goal_time: 1.6
      shoulder_pan_joint:
        trajectory: 0.1
        goal: 0.1
      shoulder_lift_joint:
        trajectory: 0.1
        goal: 0.1
      elbow_joint:
        trajectory: 0.1
        goal: 0.1
      wrist_1_joint:
        trajectory: 0.1
        goal: 0.1
      wrist_2_joint:
        trajectory: 0.1
        goal: 0.1
      wrist_3_joint:
        trajectory: 0.1
        goal: 0.1

joint_group_position_controller:
  ros__parameters:
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    interface_name: position

# 210927 YSW: Gripper Controllers
rh_p12_rn_position:
  ros__parameters:
    joints:
      - rh_p12_rn
    interface_name: effort

rh_r2_position:
  ros__parameters:
    joints:
      - rh_r2
    interface_name: effort

rh_l1_position:
  ros__parameters:
    joints:
      - rh_l1
    interface_name: effort

rh_l2_position:
  ros__parameters:
    joints:
      - rh_l2
    interface_name: effort
